// Generated by CoffeeScript 1.7.1
var app, express, http, options, path, port, sharejs;

express = require('express');

http = require('http');

path = require('path');

sharejs = require('share');

app = express();

app.set('port', process.env.PORT || 3000);

app.set('views', path.join(__dirname, '../views'));

app.set('view engine', 'html');

app.use(express.favicon());

app.use(express.logger('dev'));

app.use(express.json());

app.use(express.urlencoded());

app.use(express.methodOverride());

app.use(express.cookieParser('your secret here'));

app.use(express.session());

app.use(app.router);

app.use(require('stylus').middleware(path.join(__dirname, 'public')));

app.use(express["static"](path.join(__dirname, '../public')));

app.enable('view cache');

app.engine('html', require('hogan-express'));

require('redis');

options = {
  browserChannel: {
    cors: "*"
  },
  db: {
    type: "redis"
  }
};

sharejs.server.attach(app, options);

require('./wiki')(app);

port = 5000;

app.listen(port, function() {
  return console.log("Listening on " + port);
});
