// Generated by CoffeeScript 1.6.2
var docPresenter, gherkinDocument, render, showdown, wikiDocument;

wikiDocument = require('./builder/wikiDocument');

gherkinDocument = require('./builder/gherkinDocument');

module.exports = function(app) {
  app.get('/wiki/?', function(req, res) {
    res.writeHead(301, {
      location: '/wiki/Main'
    });
    return res.end();
  });
  app.get('/wiki/:docName', function(req, res) {
    var docName;

    docName = req.params.docName;
    return docPresenter(docName, app.model, res, wikiDocument);
  });
  return app.get('/feature/:docName', function(req, res) {
    var docName;

    docName = req.params.docName;
    return docPresenter(docName, app.model, res, gherkinDocument);
  });
};

docPresenter = function(docName, model, res, docBuilder) {
  var name;

  name = docName;
  docName = "wiki:" + docName;
  return model.getSnapshot(docName, function(error, data) {
    if (error === 'Document does not exist') {
      return model.create(docName, 'text', function() {
        var content;

        content = docBuilder(name);
        return model.applyOp(docName, {
          op: [
            {
              i: content,
              p: 0
            }
          ],
          v: 0
        }, function() {
          return render(content, name, docName, res);
        });
      });
    } else {
      return render(data.snapshot, name, docName, res);
    }
  });
};

showdown = new (require('showdown').converter)();

render = function(content, name, docName, res) {
  var markdown;

  markdown = showdown.makeHtml(content);
  return res.render('wiki', {
    content: content,
    markdown: markdown,
    name: name,
    docName: docName
  });
};
