// Generated by CoffeeScript 1.7.1
module.exports = function(name) {
  return "# " + name + " page\n\nThis wiki page is currently empty.\nYou can put some content in it with the editor on the right. As you do so, the document will update live on the left, and live for everyone else editing at the same time as you. Isn't that cool?\nThe text on the left is being rendered with markdown, so you can do all the usual markdown stuff like:\n\n- Bullet\n  - Points\n\n[links](http://google.com)\n\n[Go back to the main page](Main)";
};
